<?php
/**
 * Created by PhpStorm.
 * User: songx
 * Date: 2017/10/20
 * Time: 14:09
 */

namespace app\controllers;



use app\controllers\base\BaseActiveController;

class UserController extends BaseActiveController implements IdentityInterface {
    public $modelClass = 'app\models\User';
    /**
     * @param $token
     * @param null $type
     * @return mixed
     */
    public static function findIdentityByAccessToken($token, $type = null) {
        return static::findOne(['Authentication' => $token]);
    }

    /**
     * @inheritDoc
     */
    public function checkAccess($action, $model = null, $params = []) {
        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }


}